### ISSUE TITLE
Unfotunate reference uuid in unit test

### ISSUE THREAD

**Issue by maherm** [stochastic-technologies/shortuuid#19]
The uuid chosen in the unit tests ("12345678-1234-5678-1234-567812345678") is not the best choice for reference. I ported your library to Java (great work btw), and for that you need to consider the byte order. The uuid gets split into two 8 byte longs, which in this case are 1234567812345678 and 1234567812345678 - they are identical. At one point in the conversion i accidently switched the LSBs and MSBs, but the unit test succeded anyways. 
You might consider chosing another uuid for reference.

**Comment by skorokithakis** [comment]
Oops, thanks for that. I'll pick a random one.

**Comment by skorokithakis** [comment]
Fixed in 71d2e23977e12aa100ac052c24029f50e67d7c09.
