### ISSUE TITLE
should characters be randomised when padding is needed

### ISSUE THREAD

**Issue by cewood** [stochastic-technologies/shortuuid#24]
This is more of a question than an actual issue at this point, but I was curious if any attempt should be made to randomise the characters taken from `self._alphabet` if padding is needed for the output?

I've tried to implement this like so:
```diff
diff --git a/shortuuid/main.py b/shortuuid/main.py
index 0aa0900..6939a89 100644
--- a/shortuuid/main.py
+++ b/shortuuid/main.py
@@ -4,6 +4,7 @@ import binascii
 import math
 import os
 import uuid as _uu
+import random as _rand
 
 
 class ShortUUID(object):
@@ -24,7 +25,10 @@ class ShortUUID(object):
             output += self._alphabet[digit]
         if pad_to_length:
             remainder = max(pad_to_length - len(output), 0)
-            output = output + self._alphabet[0] * remainder
+            output = output + ''.join(
+                map(lambda a: self._alphabet[
+                    _rand.randint(0, len(self._alphabet) - 1)],
+                    range(remainder)))
         return output
 
     def _string_to_int(self, string):
```

However unfortunately this consistently fails one of the tests, and another test intermittently errors and or otherwise fails also; the tests in question are _test_consistency_ and _test_decoding_ respectively.

Maybe what I'm suggesting here is completely silly, in which case I'm just curious to understand why that's the case then.

**Comment by cewood** [comment]
Even the following approach, which isn't random, but predictably varies the padding used by iterating through `self._alphabet` fails the same _test_consistency_ check iirc.

```diff
diff --git a/shortuuid/main.py b/shortuuid/main.py
index 0aa0900..3106194 100644
--- a/shortuuid/main.py
+++ b/shortuuid/main.py
@@ -24,7 +24,8 @@ class ShortUUID(object):
             output += self._alphabet[digit]
         if pad_to_length:
             remainder = max(pad_to_length - len(output), 0)
-            output = output + self._alphabet[0] * remainder
+            output = output + ''.join(
+                map(lambda a: self._alphabet[a], range(remainder)))
         return output
 
     def _string_to_int(self, string):
```

Although both of these approaches might have other issues, for example if `self._dictionary` wasn't sufficiently long.

**Comment by skorokithakis** [comment]
Hmm, can you explain a bit why you're randomising?

**Comment by cewood** [comment]
Good question, I din't have any actual technical reason for it. I was just curious if there was any reason for or against doing this?

As for why I actually stumbled on this question/idea, it was when I was testing the short uuids with padding, I'd occasionally see them with the same trailing character(s).

20 characters is the shortest short uuid I've commonly encountered when I was testing this, but seeing multiple short uuids appear with the trailing characters '22' (the first character of the common _alphabet list) seemed a little odd, so I dug into how that was arrived at, which led me to post this question.

Feel free to close this if this if it's a non-issue/not suitable, etc.

**Comment by skorokithakis** [comment]
Hmm, I don't think we should do this, short UUIDs are reversible, and this would prevent that. There's no real reason for or against either, but I'd like to keep reversibility, if possible.

**Comment by cewood** [comment]
Fair call, thanks for the reply.
