### ISSUE TITLE
Why base57?

### ISSUE THREAD

**Issue by DavidJFelix** [stochastic-technologies/shortuuid#25]
Seems like base57 is an unnecessary distinction from base58 which already has pretty heavy standardization within Bitcoin and wide library support across languages see:

https://github.com/bitcoin/bitcoin/blob/master/src/base58.cpp#L19
https://github.com/tv42/base58/blob/master/base58.go#L13
https://github.com/keis/base58/blob/master/base58.py#L17
https://github.com/mattallty/base58/blob/master/src/Allty/Utils/Base58.php#L6
https://github.com/jrdnull/base58/blob/master/lib/base58.ex#L2
https://github.com/45678/Base58/blob/master/Base58.coffee#L3
https://github.com/luke-jr/libbase58/blob/master/base58.c#L143

Do a search of github for base57 vs base58, it's night and day.

**Comment by skorokithakis** [comment]
base58 doesn't omit the 1, but I chose to, since it can look too similar to l/I sometimes.

**Comment by DavidJFelix** [comment]
base58 is specifically designed to not have any characters which look similar. It omits lowercase L and uppercase i for the very reason that they conflict with 1. In many base58 implementation libraries, common mistakes are already marked as identical, so mistyping `I` rather than `1` is functionally the same.

I'll close this because it seems like you're pretty against it, but to me this seems like a really frivolous thing to stick to your guns about. Anyone who wants to build a library in another language because they **do** want to serialize/deserialize and get the true UUID has to reimplement base57 because you don't like 1. It's already happened once in go, and happening now in Java, which is how I ended up here.

**Comment by skorokithakis** [comment]
I don't really care about it (and replacing I/l with 1 when deserializing is a good solution), I'm just worried about potential problems with replacing the alphabet *at this point*. It would break backwards-compatibility in a big way for people who rely on the default alphabet, unfortunately.

**Comment by skorokithakis** [comment]
Also, keep in mind that ShortUUID supports custom alphabets, so if one were to reimplement it in another language, they couldn't just reuse a base58 library there either, so I'm not sure you're gaining much by adding a 1 to the default alphabet (even though it would be a one-character change to do).
